// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsr2zgykqIO9gKwcIgvrRH9bnJQXIIH0Q',
    appId: '1:416499752145:web:82a0290354dfcd3a6df9f0',
    messagingSenderId: '416499752145',
    projectId: 'iitmandi-app-stag',
    authDomain: 'iitmandi-app-stag.firebaseapp.com',
    storageBucket: 'iitmandi-app-stag.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1uJk7t77pePtDVT3r1FCvK9ls0_kUsyI',
    appId: '1:416499752145:android:d6df0627c3817c126df9f0',
    messagingSenderId: '416499752145',
    projectId: 'iitmandi-app-stag',
    storageBucket: 'iitmandi-app-stag.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG39pwdwHZw7FSLTkVxHTFuVmY-N5S9A0',
    appId: '1:416499752145:ios:1a5d4c8c24e543c66df9f0',
    messagingSenderId: '416499752145',
    projectId: 'iitmandi-app-stag',
    storageBucket: 'iitmandi-app-stag.appspot.com',
    androidClientId:
        '416499752145-05vfd747n1bhjjgnppe19pkgdkfhutpq.apps.googleusercontent.com',
    iosClientId:
        '416499752145-lb4joe3tj5i5l3fs0uj4e4tbphp39kmo.apps.googleusercontent.com',
    iosBundleId: 'io.github.amansikarwar.institute-app.stg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG39pwdwHZw7FSLTkVxHTFuVmY-N5S9A0',
    appId: '1:416499752145:ios:8765acf5fc51adf36df9f0',
    messagingSenderId: '416499752145',
    projectId: 'iitmandi-app-stag',
    storageBucket: 'iitmandi-app-stag.appspot.com',
    androidClientId:
        '416499752145-05vfd747n1bhjjgnppe19pkgdkfhutpq.apps.googleusercontent.com',
    iosClientId:
        '416499752145-vev3q3mikbscfj0pcgtdo98f0dvmdr7u.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
